# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rcorreia/projects/crispy-doom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rcorreia/projects/crispy-doom/doom-mcp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rcorreia/projects/crispy-doom/doom-mcp/CMakeFiles /home/rcorreia/projects/crispy-doom/doom-mcp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rcorreia/projects/crispy-doom/doom-mcp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named textscreen

# Build rule for target.
textscreen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 textscreen
.PHONY : textscreen

# fast build rule for target.
textscreen/fast:
	$(MAKE) $(MAKESILENT) -f textscreen/CMakeFiles/textscreen.dir/build.make textscreen/CMakeFiles/textscreen.dir/build
.PHONY : textscreen/fast

#=============================================================================
# Target rules for targets named opl

# Build rule for target.
opl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opl
.PHONY : opl

# fast build rule for target.
opl/fast:
	$(MAKE) $(MAKESILENT) -f opl/CMakeFiles/opl.dir/build.make opl/CMakeFiles/opl.dir/build
.PHONY : opl/fast

#=============================================================================
# Target rules for targets named pcsound

# Build rule for target.
pcsound: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pcsound
.PHONY : pcsound

# fast build rule for target.
pcsound/fast:
	$(MAKE) $(MAKESILENT) -f pcsound/CMakeFiles/pcsound.dir/build.make pcsound/CMakeFiles/pcsound.dir/build
.PHONY : pcsound/fast

#=============================================================================
# Target rules for targets named crispy-server

# Build rule for target.
crispy-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crispy-server
.PHONY : crispy-server

# fast build rule for target.
crispy-server/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/crispy-server.dir/build.make src/CMakeFiles/crispy-server.dir/build
.PHONY : crispy-server/fast

#=============================================================================
# Target rules for targets named crispy-doom

# Build rule for target.
crispy-doom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crispy-doom
.PHONY : crispy-doom

# fast build rule for target.
crispy-doom/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/crispy-doom.dir/build.make src/CMakeFiles/crispy-doom.dir/build
.PHONY : crispy-doom/fast

#=============================================================================
# Target rules for targets named crispy-heretic

# Build rule for target.
crispy-heretic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crispy-heretic
.PHONY : crispy-heretic

# fast build rule for target.
crispy-heretic/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/crispy-heretic.dir/build.make src/CMakeFiles/crispy-heretic.dir/build
.PHONY : crispy-heretic/fast

#=============================================================================
# Target rules for targets named crispy-hexen

# Build rule for target.
crispy-hexen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crispy-hexen
.PHONY : crispy-hexen

# fast build rule for target.
crispy-hexen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/crispy-hexen.dir/build.make src/CMakeFiles/crispy-hexen.dir/build
.PHONY : crispy-hexen/fast

#=============================================================================
# Target rules for targets named crispy-strife

# Build rule for target.
crispy-strife: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crispy-strife
.PHONY : crispy-strife

# fast build rule for target.
crispy-strife/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/crispy-strife.dir/build.make src/CMakeFiles/crispy-strife.dir/build
.PHONY : crispy-strife/fast

#=============================================================================
# Target rules for targets named crispy-setup

# Build rule for target.
crispy-setup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crispy-setup
.PHONY : crispy-setup

# fast build rule for target.
crispy-setup/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/crispy-setup.dir/build.make src/CMakeFiles/crispy-setup.dir/build
.PHONY : crispy-setup/fast

#=============================================================================
# Target rules for targets named midiread

# Build rule for target.
midiread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 midiread
.PHONY : midiread

# fast build rule for target.
midiread/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/midiread.dir/build.make src/CMakeFiles/midiread.dir/build
.PHONY : midiread/fast

#=============================================================================
# Target rules for targets named mus2mid

# Build rule for target.
mus2mid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mus2mid
.PHONY : mus2mid

# fast build rule for target.
mus2mid/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/mus2mid.dir/build.make src/CMakeFiles/mus2mid.dir/build
.PHONY : mus2mid/fast

#=============================================================================
# Target rules for targets named doom

# Build rule for target.
doom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doom
.PHONY : doom

# fast build rule for target.
doom/fast:
	$(MAKE) $(MAKESILENT) -f src/doom/CMakeFiles/doom.dir/build.make src/doom/CMakeFiles/doom.dir/build
.PHONY : doom/fast

#=============================================================================
# Target rules for targets named heretic

# Build rule for target.
heretic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 heretic
.PHONY : heretic

# fast build rule for target.
heretic/fast:
	$(MAKE) $(MAKESILENT) -f src/heretic/CMakeFiles/heretic.dir/build.make src/heretic/CMakeFiles/heretic.dir/build
.PHONY : heretic/fast

#=============================================================================
# Target rules for targets named hexen

# Build rule for target.
hexen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hexen
.PHONY : hexen

# fast build rule for target.
hexen/fast:
	$(MAKE) $(MAKESILENT) -f src/hexen/CMakeFiles/hexen.dir/build.make src/hexen/CMakeFiles/hexen.dir/build
.PHONY : hexen/fast

#=============================================================================
# Target rules for targets named strife

# Build rule for target.
strife: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strife
.PHONY : strife

# fast build rule for target.
strife/fast:
	$(MAKE) $(MAKESILENT) -f src/strife/CMakeFiles/strife.dir/build.make src/strife/CMakeFiles/strife.dir/build
.PHONY : strife/fast

#=============================================================================
# Target rules for targets named setup

# Build rule for target.
setup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 setup
.PHONY : setup

# fast build rule for target.
setup/fast:
	$(MAKE) $(MAKESILENT) -f src/setup/CMakeFiles/setup.dir/build.make src/setup/CMakeFiles/setup.dir/build
.PHONY : setup/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... crispy-doom"
	@echo "... crispy-heretic"
	@echo "... crispy-hexen"
	@echo "... crispy-server"
	@echo "... crispy-setup"
	@echo "... crispy-strife"
	@echo "... doom"
	@echo "... heretic"
	@echo "... hexen"
	@echo "... midiread"
	@echo "... mus2mid"
	@echo "... opl"
	@echo "... pcsound"
	@echo "... setup"
	@echo "... strife"
	@echo "... textscreen"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

