add_test( [==[Generic MCP: Server lifecycle]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Server lifecycle]==]  )
set_tests_properties( [==[Generic MCP: Server lifecycle]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Single method registration]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Single method registration]==]  )
set_tests_properties( [==[Generic MCP: Single method registration]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Batch method registration]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Batch method registration]==]  )
set_tests_properties( [==[Generic MCP: Batch method registration]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Route registration]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Route registration]==]  )
set_tests_properties( [==[Generic MCP: Route registration]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Event broadcasting]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Event broadcasting]==]  )
set_tests_properties( [==[Generic MCP: Event broadcasting]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Client count]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Client count]==]  )
set_tests_properties( [==[Generic MCP: Client count]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Statistics]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Statistics]==]  )
set_tests_properties( [==[Generic MCP: Statistics]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: JSON-RPC response formatting]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: JSON-RPC response formatting]==]  )
set_tests_properties( [==[Generic MCP: JSON-RPC response formatting]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Constants]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Constants]==]  )
set_tests_properties( [==[Generic MCP: Constants]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Result codes]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Result codes]==]  )
set_tests_properties( [==[Generic MCP: Result codes]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Server configuration]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Server configuration]==]  )
set_tests_properties( [==[Generic MCP: Server configuration]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Error messages]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Error messages]==]  )
set_tests_properties( [==[Generic MCP: Error messages]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Thread safety]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Thread safety]==]  )
set_tests_properties( [==[Generic MCP: Thread safety]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Server create with invalid config]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Server create with invalid config]==]  )
set_tests_properties( [==[Generic MCP: Server create with invalid config]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Generic MCP: Response buffer overflow]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Generic MCP: Response buffer overflow]==]  )
set_tests_properties( [==[Generic MCP: Response buffer overflow]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Context lifecycle]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Context lifecycle]==]  )
set_tests_properties( [==[Doom MCP: Context lifecycle]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Game loop integration]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Game loop integration]==]  )
set_tests_properties( [==[Doom MCP: Game loop integration]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Screenshot functionality]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Screenshot functionality]==]  )
set_tests_properties( [==[Doom MCP: Screenshot functionality]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Statistics]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Statistics]==]  )
set_tests_properties( [==[Doom MCP: Statistics]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Snapshot utilities]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Snapshot utilities]==]  )
set_tests_properties( [==[Doom MCP: Snapshot utilities]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: String utilities]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: String utilities]==]  )
set_tests_properties( [==[Doom MCP: String utilities]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Configuration]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Configuration]==]  )
set_tests_properties( [==[Doom MCP: Configuration]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Result codes]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Result codes]==]  )
set_tests_properties( [==[Doom MCP: Result codes]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Constants]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Constants]==]  )
set_tests_properties( [==[Doom MCP: Constants]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Snapshot to JSON]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Snapshot to JSON]==]  )
set_tests_properties( [==[Doom MCP: Snapshot to JSON]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Error messages]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Error messages]==]  )
set_tests_properties( [==[Doom MCP: Error messages]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Command queue lifecycle]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Command queue lifecycle]==]  )
set_tests_properties( [==[Doom MCP: Command queue lifecycle]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Command queue push/pop]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Command queue push/pop]==]  )
set_tests_properties( [==[Doom MCP: Command queue push/pop]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Command queue overflow]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Command queue overflow]==]  )
set_tests_properties( [==[Doom MCP: Command queue overflow]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Command result tracking]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Command result tracking]==]  )
set_tests_properties( [==[Doom MCP: Command result tracking]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: JSON command parsing]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: JSON command parsing]==]  )
set_tests_properties( [==[Doom MCP: JSON command parsing]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[Doom MCP: Custom command parser]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[Doom MCP: Custom command parser]==]  )
set_tests_properties( [==[Doom MCP: Custom command parser]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[ASCII conversion basics]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[ASCII conversion basics]==]  )
set_tests_properties( [==[ASCII conversion basics]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[ASCII conversion output dimensions]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[ASCII conversion output dimensions]==]  )
set_tests_properties( [==[ASCII conversion output dimensions]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[ASCII conversion produces valid output]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[ASCII conversion produces valid output]==]  )
set_tests_properties( [==[ASCII conversion produces valid output]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
add_test( [==[screenshot_state conversion]==] /home/rcorreia/projects/doom-mcp/build-static/tests/dmcp_tests [==[screenshot_state conversion]==]  )
set_tests_properties( [==[screenshot_state conversion]==] PROPERTIES WORKING_DIRECTORY /home/rcorreia/projects/doom-mcp/build-static/tests SKIP_RETURN_CODE 4)
set( dmcp_tests_TESTS [==[Generic MCP: Server lifecycle]==] [==[Generic MCP: Single method registration]==] [==[Generic MCP: Batch method registration]==] [==[Generic MCP: Route registration]==] [==[Generic MCP: Event broadcasting]==] [==[Generic MCP: Client count]==] [==[Generic MCP: Statistics]==] [==[Generic MCP: JSON-RPC response formatting]==] [==[Generic MCP: Constants]==] [==[Generic MCP: Result codes]==] [==[Generic MCP: Server configuration]==] [==[Generic MCP: Error messages]==] [==[Generic MCP: Thread safety]==] [==[Generic MCP: Server create with invalid config]==] [==[Generic MCP: Response buffer overflow]==] [==[Doom MCP: Context lifecycle]==] [==[Doom MCP: Game loop integration]==] [==[Doom MCP: Screenshot functionality]==] [==[Doom MCP: Statistics]==] [==[Doom MCP: Snapshot utilities]==] [==[Doom MCP: String utilities]==] [==[Doom MCP: Configuration]==] [==[Doom MCP: Result codes]==] [==[Doom MCP: Constants]==] [==[Doom MCP: Snapshot to JSON]==] [==[Doom MCP: Error messages]==] [==[Doom MCP: Command queue lifecycle]==] [==[Doom MCP: Command queue push/pop]==] [==[Doom MCP: Command queue overflow]==] [==[Doom MCP: Command result tracking]==] [==[Doom MCP: JSON command parsing]==] [==[Doom MCP: Custom command parser]==] [==[ASCII conversion basics]==] [==[ASCII conversion output dimensions]==] [==[ASCII conversion produces valid output]==] [==[screenshot_state conversion]==])
