CPMAddPackage(
  NAME yyjson
  GITHUB_REPOSITORY ibireme/yyjson
  VERSION 0.10.0
  GIT_TAG 0.10.0
  EXCLUDE_FROM_ALL YES
  SYSTEM YES
  OPTIONS "YYJSON_BUILD_TESTS OFF" "YYJSON_BUILD_MISC OFF"
)

if(DMCP_BUILD_SHARED AND TARGET yyjson)
  set_target_properties(yyjson PROPERTIES POSITION_INDEPENDENT_CODE ON)
endif()

CPMAddPackage(
  NAME cpp-httplib
  GITHUB_REPOSITORY yhirose/cpp-httplib
  VERSION 0.36.0
  GIT_TAG v0.36.0
  OPTIONS
    "HTTPLIB_USE_OPENSSL_IF_AVAILABLE OFF"
    "HTTPLIB_USE_WOLFSSL_IF_AVAILABLE OFF"
    "HTTPLIB_USE_MBEDTLS_IF_AVAILABLE OFF"
    "HTTPLIB_USE_ZLIB_IF_AVAILABLE OFF"
    "HTTPLIB_USE_BROTLI_IF_AVAILABLE OFF"
    "HTTPLIB_USE_ZSTD_IF_AVAILABLE OFF"
    "HTTPLIB_TEST OFF"
    "HTTPLIB_INSTALL OFF"
)

if(DMCP_BUILD_TESTS)
  CPMAddPackage(
    NAME Catch2
    GITHUB_REPOSITORY catchorg/Catch2
    VERSION 3.7.1
    GIT_TAG v3.7.1
    OPTIONS "CATCH_INSTALL_DOCS OFF" "CATCH_INSTALL_EXTRAS OFF"
  )
endif()
